In [1]:
# import dependencies 
import pandas as pd

In [2]:
# read in csv file and save as dataframe
df_zodiac = pd.read_csv("MBTI_types_Birthdays.csv")

In [3]:
# check dataframe
df_zodiac.head(10)

         Timestamp    Birthday Birthday.1       Zodiac MBTI Type
0   4/15/2020 4:26   10/5/2020      5-Oct        Libra      INFP
1  4/16/2020 17:02    1/1/2007      1-Jan    Capricorn      ENTP
2  4/17/2020 20:05   10/3/2006      3-Oct        Libra      INTP
3   4/15/2020 8:35    8/3/2006      3-Aug          Leo      INTP
4   4/14/2020 6:46   4/16/2006     16-Apr        Aries      ESFP
5  4/13/2020 17:04  11/29/2005     29-Nov  Sagittarius      ENTP
6  4/13/2020 22:01   3/23/2005     23-Mar        Aries      INTJ
7  4/13/2020 12:14    9/9/2004      9-Sep        Virgo      INTP
8  4/13/2020 21:35   6/20/2004     20-Jun       Gemini      ENFJ
9  4/13/2020 15:48   2/20/2004     20-Feb       Pisces      INTJ

In [4]:
df_zodiac = df_zodiac[['Timestamp', 'Birthday', 'MBTI Type']]

In [5]:
df_zodiac.head()

         Timestamp   Birthday MBTI Type
0   4/15/2020 4:26  10/5/2020      INFP
1  4/16/2020 17:02   1/1/2007      ENTP
2  4/17/2020 20:05  10/3/2006      INTP
3   4/15/2020 8:35   8/3/2006      INTP
4   4/14/2020 6:46  4/16/2006      ESFP

In [6]:
# define function to find sun sign and add in a column 

def get_sun_sign(date):
    day = date.day
    month = date.month_name()
    
    if month == 'December':
        sun_sign = 'Sagittarius' if (day < 22) else 'Capricorn'
    elif month == 'January':
        sun_sign = 'Capricorn' if (day < 20) else 'Aquarius'
    elif month == 'February':
        sun_sign = 'Aquarius' if (day < 19) else 'Pisces'
    elif month == 'March':
        sun_sign = 'Pisces' if (day < 21) else 'Aries'
    elif month == 'April':
        sun_sign = 'Aries' if (day < 20) else 'Taurus'
    elif month == 'May':
        sun_sign = 'Taurus' if (day < 21) else 'Gemini'
    elif month == 'June':
        sun_sign = 'Gemini' if (day < 21) else 'Cancer'
    elif month == 'July':
        sun_sign = 'Cancer' if (day < 23) else 'Leo'
    elif month == 'August':
        sun_sign = 'Leo' if (day < 23) else 'Virgo'
    elif month == 'September':
        sun_sign = 'Virgo' if (day < 23) else 'Libra'
    elif month == 'October':
        sun_sign = 'Libra' if (day < 23) else 'Scorpio'
    elif month == 'November':
        sun_sign = 'Scorpio' if (day < 22) else 'Sagittarius'
    else:
        sun_sign = None
        
    return sun_sign

In [7]:
# translate birthday field to datetime format
df_zodiac['Birthday'] = pd.to_datetime(df_zodiac['Birthday'],infer_datetime_format=True)

In [8]:
# create column with zodiac signs
df_zodiac['Sun_Sign'] = df_zodiac['Birthday'].apply(lambda X: get_sun_sign(X))

In [9]:
df_zodiac.head(10)

         Timestamp   Birthday MBTI Type     Sun_Sign
0   4/15/2020 4:26 2020-10-05      INFP        Libra
1  4/16/2020 17:02 2007-01-01      ENTP    Capricorn
2  4/17/2020 20:05 2006-10-03      INTP        Libra
3   4/15/2020 8:35 2006-08-03      INTP          Leo
4   4/14/2020 6:46 2006-04-16      ESFP        Aries
5  4/13/2020 17:04 2005-11-29      ENTP  Sagittarius
6  4/13/2020 22:01 2005-03-23      INTJ        Aries
7  4/13/2020 12:14 2004-09-09      INTP        Virgo
8  4/13/2020 21:35 2004-06-20      ENFJ       Gemini
9  4/13/2020 15:48 2004-02-20      INTJ       Pisces

In [10]:
sun_sign_traits = {
    "Taurus": [
        "pragmatic",
        'hardworking',
        'down to earth',
        'stable',
        'stubborn',
        'loyal',
        'resilient',
        'pleasure seeking',
        'lazy',
        'dependable'
    ],
    "Cancer": [
        'emotional',
        'intuitive',
        'spiritual',
        'takes charge',
        'loyal',
        'moody',
        'tenacious',
        'nurturing',
        'compassionate',
        'self-protective'
    ],
    "Scorpio": [
        'emotional',
        'intuitive',
        'spiritual',
        'stable',
        'secretive',
        'passionate',
        'bold',
        'assertive',
        'strategic',
        'resentful'
    ],
    "Pisces": [
        'emotional',
        'intuitive',
        'spiritual',
        'flexible',
        'empathetic',
        'imaginative',
        'compassionate',
        'artistic',
        'impressionable',
        'romantic'
    ],
    "Gemini": [
        'curious',
        'fickle',
        'indecisive',
        'flexible',
        'resourceful',
        'talkative',
        'quick-witted',
        'unreliable',
        'clever',
        'extroverted'
    ],
    'Virgo': [
        'hardworking',
        'pragmatic',
        'down to earth',
        'flexible',
        'humble',
        'practical',
        'stressed',
        'kind',
        'helpful',
        'critical'
    ],
    "Leo": [
        "confident",
        "center-of-attention",
        "stable",
        "motivated",
        "loyal",
        "fiercely-protective",
        "generous",
        "luxury-loving",
        "creative",
        "passionate"
    ],
    'Aries': [
        "creative",
        "motivated",
        "ruthless",
        "independent",
        "self-centered",
        "fearless",
        "takes charge",
        "passionate",
        "invincible",
        "empathetic"
    ],
    'Sagittarius': [
        "hilarious",
        "optimistic",
        "flexible",
        "idealistic",
        "motivated",
        "curious",
        "passionate",
        "friendly",
        "creative",
        "travel-loving"
    ],
    'Capricorn': [
        'pragmatic', 
        'hardworking', 
        'down to earth', 
        'takes charge',
        'faithful', 
        'stubborn', 
        'practical', 
        'ambitious', 
        'sensitive', 
        'confident'
    ],
    'Aquarius': [
         'curious', 
         'fickle', 
         'indecisive', 
         'stable', 
         'analytical', 
         'witty', 
         'independent', 
         'creative', 
         'innovative', 
         'rebellious'
    ],
    'Libra': [
        'curious', 
        'fickle', 
        'indecisive', 
        'takes charge', 
        'fair-minded', 
        'conflict-avoidant', 
        'romantic', 
        'gossip', 
        'social', 
        'easygoing'
    ]
}

traits = []
for sign, sign_traits in sun_sign_traits.items():
    traits.extend(sign_traits)
    
traits = list(set(traits))

for t in traits:
    df_zodiac[t] = 0

for sign, traits in sun_sign_traits.items():
    for trait in traits:
        df_zodiac.loc[df_zodiac["Sun_Sign"] == sign, trait] = 1

In [11]:
df_zodiac.columns

Index(['Timestamp', 'Birthday', 'MBTI Type', 'Sun_Sign', 'analytical', 'moody',
       'down to earth', 'fair-minded', 'practical', 'loyal', 'talkative',
       'ruthless', 'center-of-attention', 'easygoing', 'tenacious', 'stubborn',
       'motivated', 'stable', 'impressionable', 'emotional', 'stressed',
       'resentful', 'clever', 'passionate', 'artistic', 'bold', 'social',
       'compassionate', 'quick-witted', 'critical', 'lazy', 'imaginative',
       'helpful', 'luxury-loving', 'travel-loving', 'resourceful',
       'indecisive', 'flexible', 'fearless', 'romantic', 'sensitive',
       'secretive', 'extroverted', 'rebellious', 'confident', 'hilarious',
       'witty', 'gossip', 'faithful', 'humble', 'ambitious', 'fickle',
       'self-centered', 'resilient', 'hardworking', 'empathetic',
       'fiercely-protective', 'takes charge', 'creative', 'invincible',
       'unreliable', 'friendly', 'optimistic', 'curious', 'innovative',
       'pragmatic', 'spiritual', 'generous', 'self-protective',
       'conflict-avoidant', 'assertive', 'intuitive', 'idealistic',
       'nurturing', 'kind', 'strategic', 'dependable', 'pleasure seeking',
       'independent'],
      dtype='object')

In [12]:
df_zodiac.tail(30)

,Timestamp,Birthday,MBTI Type,Sun_Sign,analytical,moody,down to earth,fair-minded,practical,loyal,...,conflict-avoidant,assertive,intuitive,idealistic,nurturing,kind,strategic,dependable,pleasure seeking,independent
276,4/14/2020 11:19,1998-08-03,ENTP,Leo,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
277,4/13/2020 11:59,1998-06-08,INTJ,Gemini,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
278,4/13/2020 17:12,1998-06-01,INTJ,Gemini,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
279,4/13/2020 13:46,1998-03-09,ENFP,Pisces,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
280,4/13/2020 15:16,1997-05-15,INFP,Taurus,0,0,1,0,0,1,...,0,0,0,0,0,0,0,1,1,0
281,4/14/2020 1:59,1996-10-24,INTJ,Scorpio,0,0,0,0,0,0,...,0,1,1,0,0,0,1,0,0,0
282,4/12/2020 17:39,1996-09-13,INFJ,Virgo,0,0,1,0,1,0,...,0,0,0,0,0,1,0,0,0,0
283,4/13/2020 11:20,1996-09-07,INFJ,Virgo,0,0,1,0,1,0,...,0,0,0,0,0,1,0,0,0,0
284,4/13/2020 12:13,1995-06-19,INFJ,Gemini,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
285,4/13/2020 11:59,1995-05-29,INTJ,Gemini,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
286,4/14/2020 17:56,1995-02-03,INFP,Aquarius,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
287,4/13/2020 14:03,1994-12-04,INTJ,Sagittarius,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
288,4/13/2020 10:59,1994-02-23,INFP,Pisces,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
289,4/13/2020 17:24,1994-01-24,INTJ,Aquarius,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
290,4/14/2020 2:14,1994-01-05,INTJ,Capricorn,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
291,4/13/2020 10:43,1993-11-29,ENTJ,Sagittarius,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
292,4/13/2020 11:16,1993-08-12,ENTJ,Leo,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
293,4/13/2020 12:52,1993-04-01,INFP,Aries,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
294,4/16/2020 3:45,1993-02-21,INFP,Pisces,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
295,4/16/2020 3:45,1993-02-21,INFP,Pisces,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
296,4/16/2020 1:18,1992-09-21,ENFJ,Virgo,0,0,1,0,1,0,...,0,0,0,0,0,1,0,0,0,0
297,4/13/2020 12:43,1992-08-08,ENFJ,Leo,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
298,4/15/2020 21:24,1992-08-08,ISTP,Leo,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
299,4/14/2020 16:11,1991-02-24,ENFP,Pisces,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
300,4/13/2020 11:21,1991-02-18,ENTP,Aquarius,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
301,4/13/2020 12:38,1988-04-04,INFJ,Aries,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
302,4/15/2020 7:38,1983-07-01,INTP,Cancer,0,1,0,0,0,1,...,0,0,1,0,1,0,0,0,0,0
303,4/13/2020 20:40,1982-05-14,INFP,Taurus,0,0,1,0,0,1,...,0,0,0,0,0,0,0,1,1,0
304,4/13/2020 14:37,1982-04-07,INTJ,Aries,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
305,4/13/2020 17:53,1980-02-13,ESFJ,Aquarius,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [20]:
#Seperate features from target
y = df_zodiac["Sun_Sign"]
X = df_zodiac.drop(columns=["Sun_Sign", "Timestamp", "Birthday", "MBTI Type"])

In [21]:
#Split the data into training and testing.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

In [22]:
#Create logistic Regression Model
from sklearn.linear_model import LogisticRegression
classifer = LogisticRegression(solver='liblinear')

In [23]:
#Train the model
classifer.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [25]:
#Get training and testing data score
classifer.score(X_train, y_train)

1.0

In [26]:
classifer.score(X_test, y_test)

1.0

In [30]:
#Make predictions
predictions = classifer.predict(X_train)
results = pd.DataFrame({
    "prediction": predictions,
    "actual": y_train
})
results.head(10)

    prediction     actual
183     Taurus     Taurus
57     Scorpio    Scorpio
30   Capricorn  Capricorn
267  Capricorn  Capricorn
88       Libra      Libra
192     Taurus     Taurus
159     Cancer     Cancer
13   Capricorn  Capricorn
190     Taurus     Taurus
140     Cancer     Cancer